export const CHALLENGE_LABEL = '_domainify-challenge'
export const RECORD_VALUE_PREFIX = 'domainify-domain-verification='
export const MAX_HOSTNAME_LENGTH = 253
export const DNS_TIMEOUT_MS = 5000
export const DNS_RETRY_COUNT = 2
export const MAX_CNAME_CHAIN_LENGTH = 8
export const AUTHORITATIVE_AGREEMENT_COUNT = 2
export const DOH_TIMEOUT_MS = 5000
export const TXT_RECORD_TYPE = 16
export const DNS_RCODE_SUCCESS = 0
export const DNS_RCODE_NAME_ERROR = 3
export const CLOUDFLARE_DOH_ENDPOINT = 'https://cloudflare-dns.com/dns-query'
export const GOOGLE_DOH_ENDPOINT = 'https://dns.google/resolve'
